# -*- coding: utf-8 -*-

{
    "name": "Gestion de la paie marocaine sous Odoo",
    "version": "11.0",
    "author": "Capital Project Strategies",
    "website": "",
    "category": "HR",
    "depends": ["base", "hr", "hr_contract","account", 'kzm_hr_contract_type',
                'date_range', 'account_fiscal_period'],
    "description": u"""Gestion de la paie marocaine sous Odoo""",
    "data": [
        "data/rubriques.xml",
        "data/employee_data.xml",
        "data/ir_cron.xml",
        "security/hr_payroll_ma_security.xml",
        "security/ir.model.access.csv",
        "wizards/hours_import.xml",
        "wizards/import_rub.xml",
        "views/hr_view.xml",
        "views/config.xml",
        "views/hr_payroll_ma_view.xml",
        "views/hr_payroll_ma_sequence.xml",
        "views/hr_payroll_ma_data.xml",
        "views/res_config_setting.xml",
        "views/date_range_view.xml",
        "views/date_trimester.xml",
        "views/dh_heure_sup.xml",
        "wizards/wizard_dh_importer_rubriques.xml",
        "report/reports_view.xml",
        "report/bulletin_paie.xml",
        "report/journal_paie_bulletin.xml",
        "report/reports_excel.xml",
        ],
    'installable' : True,
}