# -*- coding: utf-8 -*-

from . import cps_expense_type
from . import cps_expense_billeterie
from . import cps_hr_expense
from . import hr_expense
from . import cps_hr_leave
from . import cps_hr_leave_lines
from . import cps_hr_horaire
from . import cps_hr_correction
from . import account_account
from . import account_move_line
from . import hr_attendance
from . import event_event
from . import res_country
from . import res_users
from . import hr_employee
from . import helpdesk_ticket
from . import res_partner
from . import res_setting
from . import hr_leave_report
from . import account_asset
from . import cps_account_move
from . import dh_service_department
from . import hr_department
from . import dh_product_category_inherite
from . import fleet_vehicule_log_services
from . import stock_move_line
from . import dh_national_days
from . import dh_flag_reference
from . import dh_government_official
from . import dh_project_type
from . import dh_national_commission
from . import dh_sector
from . import dh_support
from . import hr_project
from . import dh_strategic_objectives
from . import dh_activity_type
from . import dh_lang
from . import hr_contract
from . import dh_db_pctemployees
from . import hr_employee_dependent
from . import mail_activity
# from . import mail_mail
# from . import ir_mail_server
from . import dh_autorization_sortie
from . import ir_model
from . import mail_activity_type
from . import reports_presence_excel
from . import res_company
from . import type_attachment
from . import task_attachment
from . import dh_hr_payroll
from . import dh_purchase_order_line
from . import dh_account_payement
from . import dh_res_bank
from . import dh_product_template1
from . import merge_partner_automatic
# from . import dh_res_bank
