# -*- coding: utf-8 -*-

from . import dh_icesco_plan_strategies
from . import dh_strategies
from . import dh_icesco_goal_strategies
from . import dh_orientations
from . import dh_agreements_international
from . import dh_agreements_international_sectors
from . import dh_icesco_operational_plan
from . import dh_operational_plan_level_one
from . import dh_operational_plan_ability
from . import dh_icesco_performance_strategies
from . import dh_icesco_office
from . import dh_icesco_performance_analysis
from . import dh_government_system
from . import dh_icesco_strategic_indicator
from . import dh_icesco_operational_indicators
from . import dh_icesco_informations
from . import dh_perf_sector
from . import dh_perf_type_activity
from . import project_task
from . import project_project
from . import dh_perf_operations
from . import res_partner
from . import dh_mission
from . import dh_pilliar
from . import dh_employee
from . import hr_expense
from . import account_budget
from . import dh_agreement_type
from . import dh_agreement_categories
from . import dh_bourse
from . import dh_awards
from . import dh_chairs
from . import key_performance_indicators
from . import link_dev_goals
from . import risks_addressing
from . import account_move_line
from . import dh_no_sector_programmes
from . import dh_etapes_done
from . import dh_indicator_result_type
from . import dh_expense_purchase
from . import dh_orientation_graph
from . import dh_pilliar_graph
from . import project_task_graph
from . import analyse_budget_approved
from . import dh_pays_cible
from . import dh_contrubution
from . import analyse_budget_approved_graph
from . import dh_agreements_international_graph
from . import project_task_budget_graph
from . import dh_contribution_graph
from . import dh_involved_country
from . import dh_engaged_partner
from . import dh_sector_dpt
from . import dh_icesco_proposition